### ISSUE TITLE
Error in extension code when trying to compile and run

### ISSUE THREAD

**Issue by Naimad1CZ** [danielpinto8zz6/c-cpp-compile-run#201]
I want to use this extension, but can't:

I have latest version of C/C++ Compile Run installed (1.0.8), latest version of Visual Studio Code (1.45.1), also Mingw installed; using Windows 10.

When I hit F6 or F7 key to compile and run current C file, Visual Studio gets high CPU usage for a few seconds, and then I see in Output from Log (Window) this:
![obrazek](https://user-images.githubusercontent.com/35201314/82616971-fee1ca80-9bce-11ea-8576-839b01bb732b.png)

I get the same thing (without any Output from C/C++ Compile Run) repeatedly.

**Comment by danielpinto8zz6** [comment]
What's your vscode version?

**Comment by Naimad1CZ** [comment]
> 
> 
> What's your vscode version?

1.45.1

**Comment by danielpinto8zz6** [comment]
you have gcc on your PATH?

**Comment by danielpinto8zz6** [comment]
update extension to v1.0.9 and check if error persists please

**Comment by Fabricio967** [comment]
Hello @danielpinto8zz6 I having a similar issue and apparently its the command line changed, my environment variables works fine. I come to have this issue this evening because i past the afternoon using the VS Code and the compiler.
![image](https://user-images.githubusercontent.com/43080818/82765455-90c71e80-9ded-11ea-8eb8-edf6899eede8.png)

**Comment by danielpinto8zz6** [comment]
@Fabricio967 you have that error with v1.0.10?

**Comment by Fabricio967** [comment]
Yes

**Comment by Fabricio967** [comment]
The problem was solved when I installed a previous version (1.0.8). Only version 1.0.10 has the problem.

**Comment by Naimad1CZ** [comment]
> update extension to v1.0.10 and check if error persists please

Updated to v1.0.10 (and reloaded VS Code), issue persists in the same form.
I have gcc installed and can it use e.g. in cmd.

**Comment by danielpinto8zz6** [comment]
try new version 1.0.11

**Comment by Naimad1CZ** [comment]
> try new version 1.0.11

I still get the same error, but idk, maybe it's something wrong on my side (and I have no idea what it is or how to fix it).
But thanks a lot for effort and time!

**Comment by danielpinto8zz6** [comment]
I guess your error is related to a bug in a library I am using in the project, I'll check it

**Comment by danielpinto8zz6** [comment]
Can you check if it is your antivirus blocking?

**Comment by Naimad1CZ** [comment]
> Can you check if it is your antivirus blocking?

Hmm, interesting, restarted computer (didn't want to do before because I was working on some project; but was reloading and restarting VS Code before), disabled antivirus and it worked all right! Then enabled antivirus and it also worked all right.

Thank you a lot for fixing it!

**Comment by danielpinto8zz6** [comment]
no problem :+1:
