### ISSUE TITLE
Whether should run in an external terminal..

### ISSUE THREAD

**Issue by srikant-marvel** [danielpinto8zz6/c-cpp-compile-run#308]
**Describe the bug**

**Expected behavior**
After the `14 February` Update, **C/C++ Compile Run** no longer runs in the external terminal; I'm not sure what's causing the problem, but it shows the external terminal for a fraction of a second before disappearing.

**Screenshots**

https://user-images.githubusercontent.com/52560067/218614976-f6461fb3-e329-41d1-9f79-6429bd444f29.mp4

**Environment**
 - VSCode Version: 1.75.1

 - OS Version: 10.0.19043 N/A Build 19043 x64

**Additional context**

**Comment by danielpinto8zz6** [comment]
Hi, what terminal do you use?

**Comment by danielpinto8zz6** [comment]
It should be fixed now, Please update make sure you're on latest version and check again.

**Comment by srikant-marvel** [comment]
Now, I got the problem.
The problem is that location where the .exe files are getting stored.
I have set it somewhere else.

**Comment by danielpinto8zz6** [comment]
Did the location not exists?

**Comment by srikant-marvel** [comment]
## **Yes It exists in my program folder.**


![image](https://user-images.githubusercontent.com/52560067/218904384-525d35a1-289c-42a6-ac8f-277396ea23a8.png)


---
![image](https://user-images.githubusercontent.com/52560067/218904929-1e1d8bee-fdeb-43d5-911a-9578ccd6d8f2.png)

### And there is another warning I got today.
_Cannot read properties of undefined (reading 'setAtlas')_

**Comment by ThousandPine** [comment]
The same problem still occur when the "Output-location" is blank in version 1.0.32 ~ 1.0.35.
From the git history, it seems that this happened after "5e40e07: Merge pull request #304 from danielpinto8zz6/development

Development".

**Comment by srikant-marvel** [comment]
#### Is ther any solution to that..
@ThousandPine

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/c-cpp-compile-run/commit/ec14df45ffd49fb56fc806fbf6d84fbabbdba5e1
Should be fixed now,

@ThousandPine @srikant-marvel can you test and give feedback? 
Thank you

**Comment by ThousandPine** [comment]
The problem still exists in version 1.0.36, and the external terminal will not appear at all this time.
@danielpinto8zz6

**Comment by ThousandPine** [comment]
> The problem still exists in version 1.0.36, and the external terminal will not appear at all this time. @danielpinto8zz6

Revision: I didn't notice that it happened too fast before, but now the external terminal still appears once and exits automatically.

**Comment by ThousandPine** [comment]
> #### Is ther any solution to that..
> @ThousandPine

You can temporarily switch to the version before 1.0.32, or use the built-in terminal of vscode.
@srikant-marvel

**Comment by srikant-marvel** [comment]
## The exteranl terminal is able to hold the output screen but it is showing an error 

`C:/Msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find .exe: No such file or directory
collect2.exe: error: ld returned 1 exit status`

---
![image](https://user-images.githubusercontent.com/52560067/219241496-1e5dbf00-5826-49c7-93e7-41c585461afc.png)


@danielpinto8zz6

**Comment by danielpinto8zz6** [comment]
@ThousandPine can you test 1.0.37 please?
I've been doing some tests on windows and didn't had any problem.
If it doesn't works, please provide me your configuration

**Comment by danielpinto8zz6** [comment]
@srikant-marvel can you provide me your configuration?

**Comment by srikant-marvel** [comment]
#### The problem is only occurring when I try to change the output folder location.

**Comment by danielpinto8zz6** [comment]
You still have the problem with 1.0.37?

**Comment by srikant-marvel** [comment]
## Yes after the update the new error is showing up on the terminal..

---
![image](https://user-images.githubusercontent.com/52560067/219246366-2373e8cb-9559-45b9-bc74-80a67af5a48f.png)

**Comment by danielpinto8zz6** [comment]
What setting do you have on your windows terminal ("terminal.external.windowsExec")?

**Comment by srikant-marvel** [comment]
`C:\Program Files\Git\git-bash.exe" --cd-to-home`

**Comment by danielpinto8zz6** [comment]
Oh, now I see the problem

**Comment by danielpinto8zz6** [comment]
I bellieve it's now fixed @srikant-marvel , try 1.0.39

**Comment by srikant-marvel** [comment]
@danielpinto8zz6 The Problem is still the same change the output folder and output screen just don't hold the screen.

**Comment by danielpinto8zz6** [comment]
Are you on version 1.0.39?

**Comment by srikant-marvel** [comment]
Yep.. 👍🏼

**Comment by danielpinto8zz6** [comment]
What output location you have?

**Comment by srikant-marvel** [comment]
Same folder as before.
https://github.com/danielpinto8zz6/c-cpp-compile-run/issues/308#issuecomment-1430626793

**Comment by danielpinto8zz6** [comment]
if you change your "terminal.external.windowsExec" to "cmd.exe" does it works?

**Comment by srikant-marvel** [comment]
No luck with that either..
Not holding the output screen..

**Comment by danielpinto8zz6** [comment]
If you change your output folder name to something like: "c_cpp" without special characters and .exe does it works?

**Comment by danielpinto8zz6** [comment]
Please remember the output location is the folder where the executable should be located, not the executable itself

**Comment by srikant-marvel** [comment]
Actually, I changed the folder name and location to now there is no error..
thanks ❤️ @danielpinto8zz6

**Comment by danielpinto8zz6** [comment]
Great, glad it works 👍
